@startuml MassageShop Use Case Diagram
left to right direction
actor "User" as user

rectangle "MassageShop System" {
    usecase "Register" as regis
    usecase "Login/Logout" as log
    usecase "View\nMassageShops" as view
    usecase "Manage\nMassageShops" as man_shop
    usecase "Manage\nReservations" as man_reser
}

actor "Admin" as admin

user -- regis
user -- log
user -- view
user -- man_reser

regis -- admin
log -- admin
man_shop -- admin
man_reser -- admin

@enduml