@startuml Add Reservation (POST)
header Massage Reservation System
footer Page %page% of %lastpage%
title "Add Reservation (POST)"

participant "Client" as client
participant ":server" as server <<javascript>>
participant ":reservations" as router <<router>>
participant ":reservations" as controller <<controllers>>
participant ":Reservation" as model <<model>>
database "MongoDB" as db

client -> server : req.post('/api/v1/reservations')
activate server
server -> router : app.use('/api/v1/reservations', reservations)
activate router
router -> controller : addReservation()
activate controller

controller -> model : create(req.body)
activate model
model -> db : ReservationSchema
activate db
db --> model : saved reservation
deactivate db
model --> controller : reservation
deactivate model

controller --> client : 201 Created
deactivate controller
deactivate router
deactivate server
@enduml